Header header
float32 WheelSpeed_FL
float32 WheelSpeed_FR
float32 WheelSpeed_RL
float32 WheelSpeed_RR
float32 VehicleSpeed
float32 ThrottlePosition
uint8 SteeringWheelAngle
uint8 SteeringWheelSpeed
uint8 ActualGear
uint8 BrakePedalSt


uint8 ACTUALGEAR_P = 0
uint8 ACTUALGEAR_R = 1
uint8 ACTUALGEAR_N = 2
uint8 ACTUALGEAR_1 = 3
uint8 ACTUALGEAR_2 = 4
uint8 ACTUALGEAR_3 = 5
uint8 ACTUALGEAR_4 = 6
uint8 ACTUALGEAR_5 = 7
uint8 ACTUALGEAR_6 = 8
uint8 ACTUALGEAR_7 = 9
uint8 ACTUALGEAR_8 = 10

uint8 BRAKP_NOT_ACTUATED = 0
uint8 BRAKP_ACTUATED = 1
uint8 BRAKP_RESERVED = 2
uint8 BRAKP_ERROR = 3